console.time('Timmer');
console.log('Hello console');
console.log(4 + 8);
console.log(35);
console.log([34, 24, 15, 22]);
console.table({ Avio: 'this', message: 'error' });
console.table([34, 24, 15, 22]);
console.warn('this is a warning');
//console.clear();
console.log('Hello new  console');
console.timeEnd('Timmer');
console.assert(555 < 198, 'Age > 189 is not possible');
console.error('this is an error');
//alert('This is a alert message: ');